<a href="https://colab.research.google.com/github/mnocerino23/Numerical-Analysis/blob/main/CSCI166_HW8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question 1c:

In [301]:
import numpy as np
import numpy.linalg as nplinalg
import pandas as pd

In [302]:
newton = pd.DataFrame(columns = ['Iteration', 'Solution', 'Error', 'Residual'])

In [303]:
iteration = []
x_ns = []
errors = []
residuals = []

In [304]:
solution_1 = np.array([[-2/3], [-4/3], [4/3]])
solution_2 = np.array([[-6/7], [-12/7], [4/7]])

In [305]:
#start with an initial guess of x1 = 15, x2 = 15, x3 = 15
x1, x2, x3 = 15, 15, 15

function = np.array([[(2*x1)-(3*x2)+ x3-4], [(2*x1)+x2-x3+4], [(x1**2) + (x2**2) + (x3**2) - 4]])
print(function)
#create the jacobian which has constant values in rows one and two but the third row will
#change depending on the values of x1, x2, x3 at each iteration
Jacobian = np.array([[2, -3, 1],[2, 1, -1],[2*x1, 2*x2, 2*x3]])
print(Jacobian)

for i in range(1):
  iteration.append(i+1)
  #solve the linear system for the direction change
  v = np.linalg.solve(Jacobian, function)
  print(v)
  #update values of x1, x2, x3 by subtracting the direction change in the correct compute
  x1 = x1 - v[0]
  x2 = x2 - v[1]
  x3 = x3 - v[2]
  x_n = np.array([[x1], [x2], [x3]])
  print(x_n)
  x_ns.append(x_n)

[[ -4]
 [ 34]
 [671]]
[[ 2 -3  1]
 [ 2  1 -1]
 [30 30 30]]
[[12.33809524]
 [ 9.67619048]
 [ 0.35238095]]
[[[ 2.66190476]]

 [[ 5.32380952]]

 [[14.64761905]]]


In [306]:
newton['Iteration'] = iteration
newton['Solution'] = x_ns

In [307]:
newton

Iteration                                           Solution Error Residual
0          1  [[[2.6619047619047613]], [[5.323809523809524]]...   NaN      NaN

# Question 2c:

In [308]:
#function f(x) will be the ln(x). In python's numpy we use np.log(x) for natural log
def f(x):
  return np.log(x)

In [309]:
#the known derivative of ln(x) = 1/x
def f_prime(x):
  return (1/x)

In [310]:
def derivative_approximation(x, h):
  numerator = f(x+(2*h)) - f(x-h)
  return numerator/(3*h)

In [311]:
x_o = []
derivative_value = []
h_value = [0.5,0.25,0.125,0.0625, 0.03125,0.015625, 0.0078125, 0.00390625, 0.001953125]
derivative_approx = []
error = []

In [312]:
x_naught = 2

In [313]:
for value in h_value:
  x_o.append(x_naught)
  d_value = 1/2
  derivative_value.append(d_value)
  d_approx = derivative_approximation(2, value)
  derivative_approx.append(d_approx)
  error.append(abs(d_value - d_approx))

In [314]:
results = pd.DataFrame(columns = ['x naught', 'f prime', 'f prime approximation', 'h-value', 'error'])

In [315]:
results['x naught'] = x_o
results['f prime'] = derivative_value
results['f prime approximation'] = derivative_approx
results['h-value'] = h_value
results['error'] = error

# Final table for our approximations of first derivative of ln(x):

From our table below, we see that as the h-value is halved, the error between the approximation and the actual value of the derivative is also roughly halved at each iteration.

In [316]:
results

x naught  f prime  f prime approximation   h-value     error
0         2      0.5               0.462098  0.500000  0.037902
1         2      0.5               0.475567  0.250000  0.024433
2         2      0.5               0.486191  0.125000  0.013809
3         2      0.5               0.492658  0.062500  0.007342
4         2      0.5               0.496214  0.031250  0.003786
5         2      0.5               0.498077  0.015625  0.001923
6         2      0.5               0.499031  0.007812  0.000969
7         2      0.5               0.499514  0.003906  0.000486
8         2      0.5               0.499756  0.001953  0.000244