<a href="https://colab.research.google.com/github/mnocerino23/Numerical-Analysis/blob/main/CSCI166_HW8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question 1c:

In [333]:
import numpy as np
import numpy.linalg as nplinalg
import pandas as pd

In [334]:
newton = pd.DataFrame(columns = ['Iteration', 'Solution', 'Error', 'Residual'])

In [335]:
iteration = []
x_ns = []
errors = []
residuals = []

In [336]:
solution_1 = np.array([[-2/3], [-4/3], [4/3]])
solution_2 = np.array([[-6/7], [-12/7], [4/7]])

In [337]:
#start with an initial guess of x1 = 15, x2 = 15, x3 = 15
x1, x2, x3 = 15, 15, 15

function = np.array([[(2*x1)-(3*x2)+ x3-4], [(2*x1)+x2-x3+4], [(x1**2) + (x2**2) + (x3**2) - 4]])
print(function)
#create the jacobian which has constant values in rows one and two but the third row will
#change depending on the values of x1, x2, x3 at each iteration
Jacobian = np.array([[2, -3, 1],[2, 1, -1],[2*x1, 2*x2, 2*x3]])
print(Jacobian)

for i in range(20):
  iteration.append(i+1)
  #solve the linear system for the direction change
  v = np.linalg.solve(Jacobian, function)
  #print(v)
  #update values of x1, x2, x3 by subtracting the direction change in the correct compute
  x1 = x1 - v[0]
  x2 = x2 - v[1]
  x3 = x3 - v[2]
  x_n = np.array([[x1], [x2], [x3]])
  #print(x_n)
  x_ns.append(x_n)

[[ -4]
 [ 34]
 [671]]
[[ 2 -3  1]
 [ 2  1 -1]
 [30 30 30]]
[[12.33809524]
 [ 9.67619048]
 [ 0.35238095]]
[[[ 2.66190476]]

 [[ 5.32380952]]

 [[14.64761905]]]
[[12.33809524]
 [ 9.67619048]
 [ 0.35238095]]
[[[-9.67619048]]

 [[-4.35238095]]

 [[14.2952381 ]]]
[[12.33809524]
 [ 9.67619048]
 [ 0.35238095]]
[[[-22.01428571]]

 [[-14.02857143]]

 [[ 13.94285714]]]
[[12.33809524]
 [ 9.67619048]
 [ 0.35238095]]
[[[-34.35238095]]

 [[-23.7047619 ]]

 [[ 13.59047619]]]
[[12.33809524]
 [ 9.67619048]
 [ 0.35238095]]
[[[-46.69047619]]

 [[-33.38095238]]

 [[ 13.23809524]]]
[[12.33809524]
 [ 9.67619048]
 [ 0.35238095]]
[[[-59.02857143]]

 [[-43.05714286]]

 [[ 12.88571429]]]
[[12.33809524]
 [ 9.67619048]
 [ 0.35238095]]
[[[-71.36666667]]

 [[-52.73333333]]

 [[ 12.53333333]]]
[[12.33809524]
 [ 9.67619048]
 [ 0.35238095]]
[[[-83.7047619 ]]

 [[-62.40952381]]

 [[ 12.18095238]]]
[[12.33809524]
 [ 9.67619048]
 [ 0.35238095]]
[[[-96.04285714]]

 [[-72.08571429]]

 [[ 11.82857143]]]
[[12.33809524]
 [ 9.

In [338]:
newton['Iteration'] = iteration
newton['Solution'] = x_ns

In [339]:
newton

Iteration                                           Solution Error  \
0           1  [[[2.6619047619047613]], [[5.323809523809524]]...   NaN   
1           2  [[[-9.676190476190477]], [[-4.352380952380951]...   NaN   
2           3  [[[-22.014285714285716]], [[-14.02857142857142...   NaN   
3           4  [[[-34.352380952380955]], [[-23.70476190476190...   NaN   
4           5  [[[-46.69047619047619]], [[-33.38095238095238]...   NaN   
5           6  [[[-59.028571428571425]], [[-43.05714285714286...   NaN   
6           7  [[[-71.36666666666666]], [[-52.733333333333334...   NaN   
7           8  [[[-83.7047619047619]], [[-62.40952380952381]]...   NaN   
8           9  [[[-96.04285714285713]], [[-72.08571428571429]...   NaN   
9          10  [[[-108.38095238095237]], [[-81.76190476190476...   NaN   
10         11  [[[-120.7190476190476]], [[-91.43809523809523]...   NaN   
11         12  [[[-133.05714285714285]], [[-101.1142857142857...   NaN   
12         13  [[[-145.39523809523808]], [[-110.7904761904761...   NaN   
13         14  [[[-157.73333333333332]], [[-120.4666666666666...   NaN   
14         15  [[[-170.07142857142856]], [[-130.1428571428571...   NaN   
15         16  [[[-182.4095238095238]], [[-139.81904761904758...   NaN   
16         17  [[[-194.74761904761903]], [[-149.4952380952380...   NaN   
17         18  [[[-207.08571428571426]], [[-159.1714285714285...   NaN   
18         19  [[[-219.4238095238095]], [[-168.847619047619]]...   NaN   
19         20  [[[-231.76190476190473]], [[-178.5238095238094...   NaN   

   Residual  
0       NaN  
1       NaN  
2       NaN  
3       NaN  
4       NaN  
5       NaN  
6       NaN  
7       NaN  
8       NaN  
9       NaN  
10      NaN  
11      NaN  
12      NaN  
13      NaN  
14      NaN  
15      NaN  
16      NaN  
17      NaN  
18      NaN  
19      NaN

# Question 2c:

In [340]:
#function f(x) will be the ln(x). In python's numpy we use np.log(x) for natural log
def f(x):
  return np.log(x)

In [341]:
#the known derivative of ln(x) = 1/x
def f_prime(x):
  return (1/x)

In [342]:
def derivative_approximation(x, h):
  numerator = f(x+(2*h)) - f(x-h)
  return numerator/(3*h)

In [343]:
x_o = []
derivative_value = []
h_value = [0.5,0.25,0.125,0.0625, 0.03125,0.015625, 0.0078125, 0.00390625, 0.001953125]
derivative_approx = []
error = []

In [344]:
x_naught = 2

In [345]:
for value in h_value:
  x_o.append(x_naught)
  d_value = 1/2
  derivative_value.append(d_value)
  d_approx = derivative_approximation(2, value)
  derivative_approx.append(d_approx)
  error.append(abs(d_value - d_approx))

In [346]:
results = pd.DataFrame(columns = ['x naught', 'f prime', 'f prime approximation', 'h-value', 'error'])

In [347]:
results['x naught'] = x_o
results['f prime'] = derivative_value
results['f prime approximation'] = derivative_approx
results['h-value'] = h_value
results['error'] = error

# Final table for our approximations of first derivative of ln(x):

From our table below, we see that as the h-value is halved, the error between the approximation and the actual value of the derivative is also roughly halved at each iteration.

In [348]:
results

x naught  f prime  f prime approximation   h-value     error
0         2      0.5               0.462098  0.500000  0.037902
1         2      0.5               0.475567  0.250000  0.024433
2         2      0.5               0.486191  0.125000  0.013809
3         2      0.5               0.492658  0.062500  0.007342
4         2      0.5               0.496214  0.031250  0.003786
5         2      0.5               0.498077  0.015625  0.001923
6         2      0.5               0.499031  0.007812  0.000969
7         2      0.5               0.499514  0.003906  0.000486
8         2      0.5               0.499756  0.001953  0.000244