<a href="https://colab.research.google.com/github/mnocerino23/Numerical-Analysis/blob/main/HW9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
#write code to compute R2(1) for the following interval

In [73]:
import numpy as np
import math 
def f(x):
  return (math.exp(1))**(-x**2)

# Trapezoidal Rule function

In [74]:
#function = function whose integral we want to approximate
#a = left endpoint of interval
#b = right endpoint of interval
#n = number of trapezoids used to estimate integral

def trapezoidal_rule(function, a, b, n):
  h = (b-a)/n
  base = h/2
  heights = 0
  x_values = np.linspace(a,b,n+1)
  #print(x_values)
  for i in range(n+1):
    if i == 0 or i == n:
      heights += function(x_values[i])
    else:
      heights += 2*function(x_values[i])
  return base*heights

In [75]:
#use function from class to test my trapezoidal rule function
trapezoidal_rule(f,0,1,4)

0.7429840978003812

# Question 1c: Write a program to compute R2(h)

In [76]:
#code the function we need to integrate into g(x)
def g(x):
  return x*((math.exp(1))**(-x**2))

In [77]:
#function to compute R1(h), which uses our trapezoidal rule function twice with every call
def R_1(function, a, b , n):
  h = (b-a)/n
  numerator = ((9*trapezoidal_rule(function, a, b, 3*n)) - trapezoidal_rule(function, a, b, n))
  return numerator/8

#function to compute R2(h), which uses our R_1 function twice with every call
def R_2(function, a, b, n):
  h = (b-a)/n
  numerator = ((81*R_1(function, a, b, 3*n)) - R_1(function, a, b, n))
  return numerator/80

Now estimate the integral of our function g from 0 to 1 with an h value of one, meaning n = 1 in our parameters

In [78]:
#with h = 1, the approximation is extremely close to the true value of the integral which is 0.31606027941
R_2(g, 0, 1, 1)

0.31605356775661503

In [79]:
#as you increase h, approximation gets even closer and closer to actual value
for i in range(11):
  if i!= 0:
    print("H-value:", i,", Approximation: ", R_2(g, 0, 1, i))


H-value: 1 , Approximation:  0.31605356775661503
H-value: 2 , Approximation:  0.3160602066159818
H-value: 3 , Approximation:  0.3160602733431867
H-value: 4 , Approximation:  0.3160602783522236
H-value: 5 , Approximation:  0.3160602791380474
H-value: 6 , Approximation:  0.3160602793221608
H-value: 7 , Approximation:  0.3160602793778405
H-value: 8 , Approximation:  0.3160602793979524
H-value: 9 , Approximation:  0.3160602794062345
H-value: 10 , Approximation:  0.31606027941000725


# Question 2

In [80]:
import numpy as np

# 2a: The evaluation points, which are the roots of the provided polynomial is found printed below:

In [81]:
#numpy's poly 1d function allows us to 
polynomial = np.poly1d([1, 0, -10/9, 0, 5/21, 0])
initialPoints = polynomial.roots
initialPoints.sort()
print(initialPoints)

[-0.90617985 -0.53846931  0.          0.53846931  0.90617985]


In [82]:
#form the matrix that we will solve to 
#row one is 5 1's since f(x) = 1
rows = [[1, 1, 1, 1, 1]]

exponents = [1, 2, 3, 4]
for n in exponents:
  row = []
  for item in initialPoints:
    row.append(item**n)
  rows.append(row)

In [83]:
matrix = np.array(rows)

In [84]:
#create a matrix of all the coefficients on the wi's
matrix

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [-0.90617985, -0.53846931,  0.        ,  0.53846931,  0.90617985],
       [ 0.82116191,  0.2899492 ,  0.        ,  0.2899492 ,  0.82116191],
       [-0.74412038, -0.15612874,  0.        ,  0.15612874,  0.74412038],
       [ 0.67430689,  0.08407054,  0.        ,  0.08407054,  0.67430689]])

In [85]:
#finally we to solve a matrix equation Ax = b where b are the values of the various integrals
b = np.array([[2],
              [0],
              [2/3],
              [0],
              [2/5]])

# 2a: Solve the linear system to find the weights w1, w2, ..., w5

In [86]:
#now use numpy's linear algebra solver to solve the equation and get a column vector of the weights wi
weights = np.linalg.solve(matrix,b)
print(weights)

[[0.23692689]
 [0.47862867]
 [0.56888889]
 [0.47862867]
 [0.23692689]]


# 2b: General function gaussian_quadrature_five gives the summation of the function values at each of the appropriate xi multiplied by the corresponding weight

In [87]:
def gaussian_quadrature_five(function):
  return ((function(initialPoints[0])*weights[0][0])+ (function(initialPoints[1])*weights[1][0]) + (function(initialPoints[2])*weights[2][0]) 
  + (function(initialPoints[3])*weights[3][0]) + (function(initialPoints[4])*weights[4][0]))

In [88]:
#testing our function on a sample function from class
#if we integrate f(x) = e^-x^2 from -1 to 1 in symbolab we get the same thing so the function works
gaussian_quadrature_five(f)

1.4936639207026294

# 2c:

In [89]:
def h(x):
  return ((x**8)+ (42*(x**7)))

# Here, the actual solution to the integral from -1 to 1 of h(x) is 2/9 and our gaussian quadrature is an amazing approximation!

In [101]:
#run the five point gaussian quadrature on h(x) to approximate its integral from -1 to 1
gaussian_quadrature_five(h)

0.222222222222209

# 2d:

Note: the polynomial in question for part d is of degree ten which is not less than or equal to 2n-1. Our five point gaussian quadrature will only be exact for any polynomial of degree 9 or less. Here, testing the quadrature on the function of degree 10, we see that it provides a decent approximation but is not as close as for those of degree <= 9

In [98]:
def q(x):
  return ((x**10)+ (42*(x**7)))

Exact value for this integral = 2/11 = 0.18181818181


In [99]:
gaussian_quadrature_five(q)

0.1788863693625471

# 2e:

We must use perform u-substitution because the bounds on this integral are from 0 to 1 and our specific gaussian quadrature is only valid for an interval -1 to 1

In [100]:
def p(u):
  left = (u+1)/4
  right = (math.exp(1))**(-1*(((u+1)/2)**2))
  return left * right

Running the gaussian quadrature on this integral we see that it is more exact than the approximation via R2(1) using Rhomberg Integration/Richardson Extrapolation technique

In [94]:
gaussian_quadrature_five(p)

0.3160602943661359